# Generated by Django 4.2.5 on 2024-01-09 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_data', '0002_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 6, 29, 48, 634331, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 1, 9, 6, 29, 54, 930854, tzinfo=datetime.timezone.utc), upload_to='media/post/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 6, 30, 4, 666103, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 1, 9, 6, 30, 10, 570934, tzinfo=datetime.timezone.utc), editable=False, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
