# Generated by Django 4.2.5 on 2024-01-09 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_data', '0003_post_created_date_post_draft_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modified_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
