# Generated by Django 4.2.5 on 2024-01-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_data', '0004_post_modified_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
